### ISSUE TITLE
need help with os2world forum

### ISSUE THREAD

**Issue by dewf** [OS2World/GAME-TOYS-Trap#1]
Sorry to abuse your github issues here, but I'm trying to contact anybody connected with the os2world forum. The website is slightly broken, so it's impossible to use the "contact" system there.

Specifically I'm trying to register for the forum, but the website is erroring out when I try to submit the form (same error I get when trying to submit the 'contact' form as well). Could you please bring this to the webmaster's attention? Thank you.

**Comment by martiniturbide** [comment]
Hi. Please write me to martiniturbide@gmail.com. 
Send me your name and email address and I will register you. 

Regards

**Comment by martiniturbide** [comment]
Not an issue.
